export const MASK_TOKEN = "____";

export const MOVABLE_PHRASAL_PARTICLES = new Set([
  "up",
  "off",
  "out",
  "in",
  "on",
  "down",
  "away",
  "back",
  "over",
  "around",
  "apart",
  "through",
]);

export const POSSESSIVE_DETERMINERS = new Set([
  "my",
  "your",
  "his",
  "her",
  "its",
  "our",
  "their",
  "one's",
  "someone's",
  "somebody's",
]);

export const REFLEXIVE_PRONOUNS = new Set([
  "myself",
  "yourself",
  "himself",
  "herself",
  "itself",
  "ourselves",
  "themselves",
  "oneself",
]);

export const HUMAN_REFERENCE_TOKENS = new Set([
  "me",
  "you",
  "him",
  "her",
  "us",
  "them",
  "someone",
  "somebody",
  "anyone",
  "anybody",
  "everyone",
  "everybody",
  "person",
  "people",
  "one",
]);

export const OBJECT_REFERENCE_TOKENS = new Set([
  "it",
  "this",
  "that",
  "these",
  "those",
  "something",
  "anything",
  "everything",
  "nothing",
  "thing",
  "things",
]);

export const TOKEN_EXPANSIONS: Record<string, string[]> = {
  "ain't": ["be", "not"],
  "aren't": ["are", "not"],
  "can't": ["can", "not"],
  cannot: ["can", "not"],
  "couldn't": ["could", "not"],
  "didn't": ["did", "not"],
  "doesn't": ["does", "not"],
  "don't": ["do", "not"],
  "hadn't": ["had", "not"],
  "hasn't": ["has", "not"],
  "haven't": ["have", "not"],
  "he'd": ["he", "would"],
  "he'll": ["he", "will"],
  "he's": ["he", "is"],
  "i'd": ["i", "would"],
  "i'll": ["i", "will"],
  "i'm": ["i", "am"],
  "i've": ["i", "have"],
  "isn't": ["is", "not"],
  "it's": ["it", "is"],
  "she'd": ["she", "would"],
  "she'll": ["she", "will"],
  "she's": ["she", "is"],
  "shouldn't": ["should", "not"],
  "that's": ["that", "is"],
  "there's": ["there", "is"],
  "they'd": ["they", "would"],
  "they'll": ["they", "will"],
  "they're": ["they", "are"],
  "they've": ["they", "have"],
  "wasn't": ["was", "not"],
  "we'd": ["we", "would"],
  "we'll": ["we", "will"],
  "we're": ["we", "are"],
  "we've": ["we", "have"],
  "weren't": ["were", "not"],
  "won't": ["will", "not"],
  "wouldn't": ["would", "not"],
  "you're": ["you", "are"],
  "you've": ["you", "have"],
};

export const TOKEN_PATTERN = /[A-Za-z]+(?:['-][A-Za-z]+)?|[^A-Za-z\s]+/g;
